### ISSUE TITLE
Error running project when connected to vsts

### ISSUE THREAD

**Issue by joaosilva2313** [SharePoint/sp-dev-fx-vs-extension#24]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you.

#### Category
[ ] Question
[x ] Bug
[ ] Enhancement

#### Versions
[ x   ]  Visual Studio version (Help > About)
[    ]  SPFx Generator version (`npm list -g @microsoft/generator-sharepoint`)

#### Expected or Desired Behavior
When press F5, run the project

#### Observed Behavior
![image](https://user-images.githubusercontent.com/31274438/32323681-c094e3b2-bfc0-11e7-8e7b-c4e20eea103b.png)

#### Steps to Reproduce
1. Create Project
2. Add To Source Control (VSTS + TFS)
3. Check-in all files
4. With this defined in workspace "Location: Server"
![image](https://user-images.githubusercontent.com/31274438/32323519-2a957c64-bfc0-11e7-84ec-d2a2c077b50f.png)
5. Run F5
got the error
![image](https://user-images.githubusercontent.com/31274438/32323669-b24a9482-bfc0-11e7-854b-789d8a23d1d7.png)

#### Submission Guidelines

Thanks for your contribution! Sharing is caring.

**Comment by eshupps** [comment]
If you look at what the build process is doing, it needs to update the [ProjectName].manifest.json file. But you have the file locked via the checkin, so it's seeing the read-only flag and throwing an access denied error. It is best to exclude files that are generated as the result of the build process from check-in. Other developers should generate output files themselves when they do a build or have them generated automatically during a team build. It's the same as adding the contents of /bin/debug or /bin/release to source control in a typical ASP.NET application - the build will fail because the files cannot be overwritten.

Have a look at the following project structure. This is a demo project that is also checked into TFS and doing automated builds on each checkin. Note the exclusion of certain folders. The contents of these folders will be generated when "gulp build" and "gulp package-solution" are run - they don't need to be (and shouldn't be) checked into TFS.

<img width="304" alt="screen shot 2017-11-02 at 7 06 18 am" src="https://user-images.githubusercontent.com/12194404/32325386-c554ade8-bf9c-11e7-8dc2-8928d52e82a1.png">

**Comment by joaosilva2313** [comment]
Sorry for the late answer. I have the project configured like that
![image](https://user-images.githubusercontent.com/31274438/32405317-e76a099a-c15a-11e7-9351-517a07c0ff53.png)
I can't run it, as soon as i change the Local Workspace, to Server.
All the files in the "lib" folder get "read only"
I can see you have that folder included, but should it be included?

**Comment by eshupps** [comment]
This functionality is "by design" when working with Visual Studio workspaces in Server mode. From the  TFS docs at [https://docs.microsoft.com/en-us/vsts/tfvc/decide-between-using-local-server-workspace](https://docs.microsoft.com/en-us/vsts/tfvc/decide-between-using-local-server-workspace): 

> When you are offline in a server workspace, you cannot work with your local files because they are read-only until you check them out. You can check out files only from Solution Explorer, and only after you switch to offline mode (as explained below). While you're offline, you can't perform any other operations, such as add, delete, rename, or undo.

Server mode is not designed for interactive file updates; rather, it is meant to emulate a "publish to IIS" type of experience. The Gulp task chain includes certain assumptions, one of which is updates to the manifest files during build and publish. This works best in Local mode. You can, of course, modify the Gulp tasks yourself but I don't recommend interrupting the chain of crucial file updates. Simply run in Local mode and it won't be an issue.

**Comment by joaosilva2313** [comment]
Ok, thanks. I will start working with it on Local mode.
Thanks for the help and great job on the template, just installed the new version 1.3.3
